<form id="text-form" >
    <div id="discount" class="discount">
        <div id="newblock">
            <label for="text"><?php echo $this->__('Your text') ?></label>
            <div class="field-wrapper">
                <input class="input-text" type="text" id="text" name="text" placeholder="<?php echo $this->getLastText(); ?>"  />
                <div class="button-wrapper">
                    <button type="submit" id="submit"  class="button2"><span><?php echo $this->__('Change') ?></span></button>
                </div>
            </div>
        </div>
    </div>
</form>