<div id="box_form">
    <?php
        echo $this->getLayout()->createBlock('newblock/newblock')->setTemplate('newblock/newblock_form.phtml')->toHtml();
    ?>
</div>

<script>
    function observeButton() {
        $('submit').observe('click', function () {

            var reloadurl = '<?php echo $this->getUrl('newblock/index/saveLastText') ?>';
            var form = $('text-form');
            var input = form['text'];
            var text = Form.Element.getValue(input);

            new Ajax.Request(reloadurl, {
                method: 'post',
                parameters: {'text':text},
                onComplete: function (transport) {
                    $("newblock").innerHTML = transport.responseText;
                    observeButton_2();
                }
            });
        });
    };

    function observeButton_2(event) {

        $("box_form").observe('click', function() {
            var reloadurl = '<?php echo $this->getUrl('newblock/index/getUpdate') ?>';

            new Ajax.Request(reloadurl, {
                onSuccess: function (response) {
                    $("box_form").innerHTML = response.responseText;
                }
            });
        });
        event.preventDefault();
    };

    document.observe('dom:loaded', function() {
        observeButton();
    });

</script>
